"""Build the Ironlark drone: its parts (tools/drone_meshes.py in Blender), a carbon weave texture,
and protos/IronlarkDrone.proto, which keeps the ArduPilot Iris flight model and carries the sensor
rig of config/sensors.json.

    .venv/bin/python tools/build_drone.py
"""
import json
import subprocess
import sys
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "protos"
PARTS = OUT / "drone"
sys.path.insert(0, str(ROOT / "tools"))

# PBR materials, Webots colors (sRGB).
MATERIALS = {
    "paint": 'baseColor 0.11 0.12 0.13 roughness 0.32 metalness 0',
    "accent": 'baseColor 0.95 0.42 0.08 roughness 0.38 metalness 0',
    "carbon": ('baseColorMap ImageTexture { url "drone/carbon.png" } '
               'normalMap ImageTexture { url "drone/carbon_normal.png" } roughness 0.28 metalness 0'),
    "battery": 'baseColor 0.2 0.21 0.22 roughness 0.6 metalness 0',
    "metal_dark": 'baseColor 0.2 0.2 0.22 roughness 0.35 metalness 1',
    "metal": 'baseColor 0.86 0.87 0.89 roughness 0.22 metalness 1',
    "metal_black": 'baseColor 0.05 0.05 0.055 roughness 0.4 metalness 0.6',
    "rubber": 'baseColor 0.03 0.03 0.03 roughness 0.9 metalness 0',
    "glass": 'baseColor 0.02 0.025 0.03 roughness 0.04 metalness 0',
    "gps": 'baseColor 0.85 0.86 0.86 roughness 0.45 metalness 0',
    "led_red": 'baseColor 0.3 0 0 emissiveColor 1 0.05 0.02 emissiveIntensity 6 roughness 0.3 metalness 0',
    "led_green": 'baseColor 0 0.3 0 emissiveColor 0.05 1 0.1 emissiveIntensity 6 roughness 0.3 metalness 0',
    "led_white": 'baseColor 0.3 0.3 0.3 emissiveColor 1 1 1 emissiveIntensity 6 roughness 0.3 metalness 0',
}
PROP = 'baseColor 0.035 0.035 0.04 roughness 0.45 metalness 0'
DISC = 'baseColor 0.05 0.05 0.06 transparency 0.82 roughness 0.5 metalness 0'
# The Iris's motors: thrust point, spin sign (thrust constant), the propeller mesh.
MOTORS = [((0.13, -0.22, 0.023), 1, "ccw"), ((-0.13, 0.20, 0.023), 1, "ccw"),
          ((0.13, 0.22, 0.023), -1, "cw"), ((-0.13, -0.20, 0.023), -1, "cw")]


def carbon_textures():
    """A 2 x 2 twill of 3 mm tows: albedo with the fibres' sheen, and a normal map of the weave."""
    size, tows = 512, 16
    y, x = np.mgrid[0:size, 0:size] / size * tows
    over = ((np.floor(x) + np.floor(y)) % 4) < 2  # which tow lies on top: warp or weft
    along = np.where(over, x % 1.0, y % 1.0)
    across = np.where(over, y % 1.0, x % 1.0)
    height = np.sin(np.pi * across) * (0.6 + 0.4 * np.sin(np.pi * along))
    fibre = 0.5 + 0.5 * np.sin(across * np.pi * 14.0)
    albedo = (0.035 + 0.03 * height * fibre)[..., None] * np.array([1.0, 1.02, 1.06])
    Image.fromarray(np.round(np.clip(albedo, 0, 1) ** (1 / 2.2) * 255).astype(np.uint8)).save(PARTS / "carbon.png")
    dy, dx = np.gradient(height * 2.0)
    normal = np.dstack([-dx * size / tows / 20, dy * size / tows / 20, np.ones_like(height)])
    normal /= np.linalg.norm(normal, axis=2, keepdims=True)
    Image.fromarray(np.round((normal * 0.5 + 0.5) * 255).astype(np.uint8)).save(PARTS / "carbon_normal.png")


def pose(sensor):
    t, r = sensor["translation"], sensor["rotation"]
    return f"translation {t[0]} {t[1]} {t[2]}\n        rotation {r[0]} {r[1]} {r[2]} {r[3]}"


def shape(material, appearance, mesh):
    return f"""Shape {{
        appearance PBRAppearance {{ {appearance} }}
        geometry Mesh {{ url "drone/{mesh}.obj" }}
        castShadows {"FALSE" if material in ("prop_disc", "glass") else "TRUE"}
      }}"""


def proto(config):
    imu, lidar, camera = config["imu"], config["lidar"], config["camera"]
    body = "\n      ".join(shape(m, a, m) for m, a in MATERIALS.items())
    propellers = []
    for i, (thrust, sign, mesh) in enumerate(MOTORS, 1):
        x, y, z = thrust
        propellers.append(f"""Propeller {{
        shaftAxis 0 0 1
        centerOfThrust {x} {y} {z}
        thrustConstants {0.0012 * sign} 0
        torqueConstants 5.0e-04 0
        device RotationalMotor {{
          name "m{i}_motor"
          maxVelocity 100
          maxTorque 30
          multiplier {sign}
        }}
        slowHelix Solid {{
          translation {x} {y} {z}
          children [
            {shape("prop", PROP, "prop_" + mesh)}
          ]
        }}
        fastHelix Solid {{
          translation {x} {y} {z}
          children [
            {shape("prop_disc", DISC, "prop_disc")}
          ]
        }}
      }}""")
    propellers = "\n      ".join(propellers)
    return f"""#VRML_SIM R2025a utf8
# Ironlark's drone, generated by tools/build_drone.py: the ArduPilot Iris flight model (motors,
# propeller constants, mass, inertia, collision box and its noiseless accelerometer, GPS, gyro and
# inertial unit, which ArduPilot reads and which serve as ground truth) with a new body and the
# sensor rig of config/sensors.json (IMU, LiDAR, camera), read by controllers/flight_bridge.

PROTO IronlarkDrone [
  field  SFVec3f     translation     0 0 0
  field  SFRotation  rotation        0 0 1 0
  field  SFString    name            "Ironlark"
  field  SFString    controller      "<none>"
  field  MFString    controllerArgs  []
  field  SFBool      supervisor      FALSE
  field  SFBool      synchronization TRUE
]
{{
  Robot {{
    translation IS translation
    rotation IS rotation
    controller IS controller
    controllerArgs IS controllerArgs
    supervisor IS supervisor
    synchronization IS synchronization
    name IS name
    children [
      {body}
      {propellers}
      Accelerometer {{
      }}
      GPS {{
      }}
      Gyro {{
      }}
      InertialUnit {{
      }}
      Pose {{
        {pose(imu)}
        children [
          Accelerometer {{
            name "{imu['name']} accelerometer"
          }}
          Gyro {{
            name "{imu['name']} gyro"
          }}
          InertialUnit {{
            name "{imu['name']} inertial unit"
          }}
        ]
      }}
      Lidar {{
        {pose(lidar)}
        name "{lidar['name']}"
        horizontalResolution {lidar['horizontal_resolution']}
        fieldOfView {lidar['field_of_view']}
        verticalFieldOfView {lidar['vertical_field_of_view']}
        tiltAngle {lidar['tilt_angle']}
        numberOfLayers {lidar['render_layers']}
        near 0.05
        minRange {lidar['min_range']}
        maxRange {lidar['max_range']}
        noise {lidar['noise']}
        projection "cylindrical"
        type "fixed"
      }}
      Camera {{
        {pose(camera)}
        name "{camera['name']}"
        fieldOfView {camera['field_of_view']}
        width {camera['width']}
        height {camera['height']}
        near {camera['near']}
        exposure 2.0
        bloomThreshold -1
        ambientOcclusionRadius 2
      }}
    ]
    boundingObject Box {{
      size 0.47 0.47 0.11
    }}
    physics Physics {{
      density -1
      mass 1.5
      centerOfMass [ 0 0 0 ]
      inertiaMatrix [
        2.9125e-02 2.9125e-02 5.5225e-02
        0 0 0
      ]
    }}
  }}
}}
"""


def main():
    from forest_pipeline import blender_executable

    PARTS.mkdir(parents=True, exist_ok=True)
    subprocess.run([str(blender_executable()), "--background", "--python-exit-code", "1", "--python", str(ROOT / "tools/drone_meshes.py"),
                    "--", "--out", str(PARTS)], check=True, stdout=subprocess.DEVNULL)
    carbon_textures()
    config = json.loads((ROOT / "config/sensors.json").read_text())
    (OUT / "IronlarkDrone.proto").write_text(proto(config))
    print("Drone ready:", OUT / "IronlarkDrone.proto")


if __name__ == "__main__":
    main()
