"""Build the Ironlark pine-forest Webots world from export_forest.py output.

Usage:
    python3 build_forest_world.py --build <forest-build> --source <textures>
        --out <worlds/pine_forest>

Converts the cache's Y-up mesh convention to the flight stack's ENU frame.
Keeps authored placements and source UVs, shares geometry and materials, and
writes the world, camera/map metadata and build manifest.

Deterministic: all randomness is seeded. Tree collision beyond the home
vicinity arrives with the navigation phase (no autonomy reads it yet).
"""

import argparse
import hashlib
import json
import math
import re
import shutil
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageOps

import forest_backdrop
import forest_edge
import forest_valley
import forest_valley
from forest_view import CAMERAS, ORIGIN, REGION, VIEW_CEILING, VIEW_MARGIN

sys.path.insert(
    0, str(Path(__file__).resolve().parents[1] / "controllers/flight_observer")
)
from minimap import look_at

COLLIDER_RADIUS = 25.0  # invisible trunk colliders within this range of home
# ---------------------------------------------------------------- obj helpers


def enu(v):
    """Legacy export cache (X,Y-up,Z) -> flight/world ENU, a proper rotation."""
    return (v[0], -v[2], v[1])


def copy_mesh(src, dst):
    with open(src) as fi, open(dst, "w") as fo:
        for line in fi:
            if line.startswith(("v ", "vn ")):
                kind, *v = line.split()
                fo.write(kind + " %.6f %.6f %.6f\n" % enu(list(map(float, v[:3]))))
            else:
                fo.write(line)


# Blender->Webots frame change as a rotation matrix (and its transpose).
C_FWD = np.array([[1, 0, 0], [0, 0, 1], [0, -1, 0]], dtype=np.float64)


def mat_to_axis_angle(m):
    """Rotation matrix -> Webots (x, y, z, angle). Re-orthogonalized."""
    u, _, vt = np.linalg.svd(np.array(m, dtype=np.float64).reshape(3, 3))
    r = u @ vt
    if np.linalg.det(r) < 0:
        u[:, -1] = -u[:, -1]
        r = u @ vt
    trace = (np.trace(r) - 1.0) / 2.0
    angle = math.acos(max(-1.0, min(1.0, trace)))
    if angle < 1e-9:
        return (0.0, 1.0, 0.0, 0.0)
    if angle > math.pi - 1e-6:
        # 180 deg: axis from the largest diagonal (sign from off-diagonals).
        k = int(np.argmax(np.diag(r)))
        axis = [r[k, 0], r[k, 1], r[k, 2]]
        axis[k] += 1.0
        n = math.sqrt(sum(a * a for a in axis))
        axis = [a / n for a in axis]
        return (axis[0], axis[1], axis[2], math.pi)
    s = 2.0 * math.sin(angle)
    return (
        (r[2, 1] - r[1, 2]) / s,
        (r[0, 2] - r[2, 0]) / s,
        (r[1, 0] - r[0, 1]) / s,
        angle,
    )


def cover_placement(mat_blender):
    """Cover instance basis -> (uniform scale, axis-angle) in Webots frame."""
    w = C_FWD @ np.array(mat_blender, dtype=np.float64).reshape(3, 3) @ C_FWD.T
    s = float(np.linalg.norm(w, axis=0).mean())
    return s, mat_to_axis_angle(w / s)


def tree_placement(matrix, base_z, home):
    """Retain an authored instance transform after rebasing its mesh at Z=0."""
    matrix = np.asarray(matrix, dtype=np.float64)
    position = matrix[:3, 3] + matrix[:3, :3] @ [0, 0, base_z] - home
    scales = np.linalg.norm(matrix[:3, :3], axis=0)
    rotation = matrix[:3, :3] / scales
    if np.linalg.det(rotation) < 0:
        scales[0] *= -1
        rotation[:, 0] *= -1
    return {
        "pos": C_FWD @ position,
        "scale": scales[[0, 2, 1]],
        "aa": mat_to_axis_angle(C_FWD @ rotation @ C_FWD.T),
        "matrix": matrix,
    }


WORLD_TEMPLATE = """#VRML_SIM R2025a utf8
# Generated by tools/build_forest_world.py — do not edit.

EXTERNPROTO "../protos/IronlarkDrone.proto"

WorldInfo {{
  title "Ironlark — pine forest"
  basicTimeStep 2
  FPS 30
  randomSeed 7
  coordinateSystem "ENU"
}}
DEF IRONLARK_VIEW Viewpoint {{
  orientation {view_ori}
  position {view_pos}
  follow "Ironlark"
  fieldOfView 1.0
  # The source's view: Filmic "Medium High Contrast" at exposure +1 (x2), and no bloom (Cycles has none).
  exposure 2.0
  bloomThreshold -1
  ambientOcclusionRadius 2
  # The viewer stays over the exported region and above the ground.
  boundsMin {bounds_min}
  boundsMax {bounds_max}
  groundClearance 0.5
}}
Background {{
  skyColor [ 0.70 0.76 0.79 ]
  {sky_fields}
  luminosity 1{light_occlusion}
}}
{fog}
# The source's two suns: strength in W/m² as intensity, linear color in sRGB.
# The main sun casts through cascaded shadow maps (Webots patch 0011).
DirectionalLight {{
  direction 0.272788 -0.814025 -0.512786
  color 1 0.9276 0.7243
  intensity 5
  castShadows TRUE
}}
DirectionalLight {{
  direction -0.148121 -0.845642 -0.512786
  color 1 0.8651 0.6049
  intensity 1
  castShadows FALSE
}}
Solid {{
  translation 0 0 0
  children [
    {terrain_shapes}
  ]
  name "terrain"
  boundingObject Mesh {{ url "meshes/terrain.obj" }}
}}
Solid {{
  translation 0 0 0
  children [
    Shape {{
      # The source's river_flow: clear water (white base, transmission 1 but foam,
      # roughness 0, IOR 1.333) with flowing white foam (patch 0010). Its volume
      # absorption (0.02 per metre) is negligible over the river's depth.
      appearance PBRAppearance {{
        baseColor 1 1 1
        roughness 0
        metalness 0
        transmission 1
        flowFoam 1
      }}
      geometry Mesh {{ url "meshes/river.obj" }}
    }}
  ]
  name "river"
}}
# Past the source's edges: its ground and forest mirrored, falling away to a valley
# (tools/forest_edge.py, tools/forest_valley.py).
Group {{
  children [
    {edge_shapes}
  ]
}}
{tree_solids}
# A visible home pad. Its top is flush with the flattened ground disc.
Solid {{
  translation 0 0 {pad_y:.3f}
  children [
    Shape {{
      appearance PBRAppearance {{
        baseColor 0.9 0.65 0.15
        roughness 1
        metalness 0
      }}
      geometry Cylinder {{ height 0.04 radius 0.8 }}
    }}
  ]
  name "home pad"
}}
DEF IRONLARK_DRONE IronlarkDrone {{
  translation 0 0 {drone_y:.3f}
  name "Ironlark"
  controller "flight_bridge"
}}
Robot {{
  children [
    Display {{
      width 320
      height 294
      name "world map"
    }}
  ]
  name "flight evaluator"
  supervisor TRUE
  controller "flight_observer"
}}
"""

VISUAL_INSTANCES = []
COPIED_RESOURCES = {}


def copy_resource(source, out, convert_mesh=False):
    """Byte-identical assets get one URL, including across tree variants."""
    with source.open("rb") as stream:
        key = (hashlib.file_digest(stream, "sha256").hexdigest(), convert_mesh)
    if key not in COPIED_RESOURCES:
        url = "meshes/" + source.name
        if convert_mesh:
            copy_mesh(source, out / url)
        else:
            shutil.copyfile(source, out / url)
        COPIED_RESOURCES[key] = url
    return COPIED_RESOURCES[key]


def light_signature(build, out):
    """Invalidate canopy lighting when its actual geometry or alpha changes."""
    digest = hashlib.sha256(json.dumps(VISUAL_INSTANCES, sort_keys=True).encode())
    # Meshes, and the textures whose alpha masks the light (RGBA PNGs: the bake treats the rest as
    # opaque, whatever their colour).
    def masks_light(path):
        with path.open("rb") as stream:
            header = stream.read(26)
        return len(header) == 26 and header[25] == 6

    urls = {record["mesh"] for record in VISUAL_INSTANCES}
    urls |= {record["texture"] for record in VISUAL_INSTANCES if record["texture"] and masks_light(out / record["texture"])}
    paths = [out / url for url in sorted(urls)]
    paths += [
        build / "terrain.obj",
        Path(__file__).with_name("bake_forest_light.py"),
        Path(__file__).with_name("forest_terrain.py"),
    ]
    for path in paths:
        with path.open("rb") as stream:
            digest.update(hashlib.file_digest(stream, "sha256").digest())
    return digest.hexdigest()


def shape_fields(mesh, tex, normal="", roughness="", shadow=True):
    # All 53 source materials are alpha-hashed: mask texels, never blend them.
    normal_field = f'normalMap ImageTexture {{ url "{normal}" }}' if normal else ""
    roughness_field = f'roughnessMap ImageTexture {{ url "{roughness}" }}' if roughness else ""
    return f"""          appearance PBRAppearance {{
            baseColorMap ImageTexture {{ url "{tex}" }}
            {normal_field}
            {roughness_field}
            roughness 0.9
            metalness 0
            alphaCutoff 0.5
          }}
          geometry Mesh {{ url "{mesh}" }}
          castShadows {"TRUE" if shadow else "FALSE"}"""



COLLIDER = """Solid {{
  translation {x:.3f} {z:.3f} {y:.3f}
  rotation {rotation}
  children [
  ]
  boundingObject Cylinder {{
    height {h:.2f}
    radius {r:.2f}
  }}
  name "trunk collider {i}"
}}
"""


def find_texture(source, image_name):
    """Resolve a Blender image name to a source PNG path."""
    if not image_name:
        return None
    image_name = re.sub(r"(\.png|\.jpg)\.\d+$", r"\1", image_name)
    candidates = [source / (image_name + ".png"), source / image_name]
    for c in candidates:
        if c.is_file():
            return c
    matches = sorted(source.glob(image_name + ".*"))
    return matches[0] if matches else None


def build_cover_textures(source, build, out):
    """One photographic material per atlas, shared across all asset variants."""
    assets = json.loads((build / "cover_assets.json").read_text())
    index, prepared = {}, {}
    for name, meta in assets.items():
        textures = meta.get("textures") or {}
        first = next(iter(textures.values()), {})
        diff, alpha = first.get("diff"), first.get("alpha")
        src = find_texture(source, diff) if diff else None
        if src is None:
            raise RuntimeError(f"Missing cover albedo: {name}: {diff}")
        key = (diff, alpha, first.get("invert_alpha", False))
        if key not in prepared:
            safe = "material_" + re.sub(r"\W", "_", diff) + ".png"
            img = Image.open(src).convert("RGB")
            img = img.resize((1024, 1024), Image.Resampling.LANCZOS)
            asrc = find_texture(source, alpha) if alpha else None
            if asrc:
                a = (
                    Image.open(asrc)
                    .convert("L")
                    .resize(img.size, Image.Resampling.LANCZOS)
                )
                if first.get("invert_alpha"):
                    a = ImageOps.invert(a)
                img.putalpha(a)
            img.save(out / "meshes" / safe)
            prepared[key] = "meshes/" + safe
        index[name] = prepared[key]
    return index


def prepare_visual_trees(source, build, out):
    """Source-authored branches and twigs, baked before tree evaluation."""
    meta = json.loads((build / "visual_trees.json").read_text())
    material_images = json.loads((build / "material_images.json").read_text())
    atlas = json.loads((build / "twig_atlas.json").read_text())
    prepared = {}
    for species, cards in atlas.items():
        img = Image.new("RGBA", (2048, 2048))
        normals = Image.new("RGB", (2048, 2048), (128, 128, 255))
        for card in cards:
            cell = (
                Image.open(build / card["file"])
                .convert("RGBA")
                .resize((512, 512), Image.Resampling.LANCZOS)
            )
            # Alpha is kept at full precision. No hard threshold erases needles.
            img.paste(cell, ((card["cell"] % 4) * 512, (card["cell"] // 4) * 512))
            if "normal" in card:
                cell = (
                    Image.open(build / card["normal"])
                    .convert("RGB")
                    .resize((512, 512), Image.Resampling.LANCZOS)
                )
                normals.paste(
                    cell, ((card["cell"] % 4) * 512, (card["cell"] // 4) * 512)
                )
        img.save(out / f"meshes/twigs_{species}.png")
        normals.save(out / f"meshes/twigs_{species}_normal.png")
    for variant, parts in meta["variants"].items():
        baked_path = build / f"baked_{variant}.json"
        baked = json.loads(baked_path.read_text()) if baked_path.exists() else {}
        for part in parts:
            part["mesh_url"] = copy_resource(
                build / part["file"], out, convert_mesh=True
            )
            if part.get("atlas", part["foliage"]):
                species = part.get(
                    "atlas_name", "pine" if "pine" in part["material"] else "fir"
                )
                part["tex"] = f"meshes/twigs_{species}.png"
                part["normal"] = f"meshes/twigs_{species}_normal.png"
                continue
            if part["material"] in baked:
                for suffix, key in [
                    ("diff", "tex"),
                    ("normal", "normal"),
                    ("rough", "roughness"),
                ]:
                    name = baked[part["material"]][suffix]
                    part[key] = copy_resource(build / name, out)
                continue
            material = part["material"].split(".")[0]
            for suffix, key in [
                ("diff", "tex"),
                ("nor_gl", "normal"),
                ("rough", "roughness"),
            ]:
                images = material_images.get(part["material"], [])
                match = next(
                    (
                        n
                        for n in images
                        if {"tex": "diff", "normal": "nor_gl", "roughness": "rough"}[
                            key
                        ]
                        in n
                    ),
                    None,
                )
                src = (
                    find_texture(source, match)
                    if match
                    else source / f"{material}_{suffix}.png"
                )
                if src is None or not src.exists():
                    if key == "tex":
                        raise RuntimeError(f"Missing tree material {src}")
                    continue
                alpha = (
                    find_texture(source, part.get("textures", {}).get("alpha", ""))
                    if key == "tex" and part["foliage"]
                    else None
                )
                cache_key = (
                    src,
                    alpha,
                    part.get("textures", {}).get("invert_alpha", False),
                )
                if cache_key in prepared:
                    part[key] = prepared[cache_key]
                    continue
                name = f"material_{material}_{suffix}.png"
                img = (
                    Image.open(src)
                    .convert("RGB")
                    .resize((1024, 1024), Image.Resampling.LANCZOS)
                )
                if key == "tex" and part["foliage"]:
                    if alpha:
                        mask = (
                            Image.open(alpha)
                            .convert("L")
                            .resize(img.size, Image.Resampling.LANCZOS)
                        )
                        if part["textures"].get("invert_alpha"):
                            mask = ImageOps.invert(mask)
                        img.putalpha(mask)
                img.save(out / "meshes" / name)
                part[key] = "meshes/" + name
                prepared[cache_key] = part[key]
    return meta["variants"]


def axis_angle_matrix(axis, angle):
    x, y, z = np.asarray(axis, dtype=np.float64) / np.linalg.norm(axis)
    c, s, C = math.cos(angle), math.sin(angle), 1 - math.cos(angle)
    return np.array(
        [
            [c + x * x * C, x * y * C - z * s, x * z * C + y * s],
            [y * x * C + z * s, c + y * y * C, y * z * C - x * s],
            [z * x * C - y * s, z * y * C + x * s, c + z * z * C],
        ]
    )


def place_tree_part(parts, part, pos, aa, scale):
    """Record one tree part's world transform, as its Transform node would have had."""
    translation = enu(list(pos))
    axis = enu(list(aa[:3]))
    sx, sy, sz = scale[0], scale[2], scale[1]  # legacy (x, y-up, z) scale to ENU
    VISUAL_INSTANCES.append(
        {
            "mesh": part["mesh_url"],
            "texture": part["tex"],
            "translation": list(translation),
            "rotation": [*axis, aa[3]],
            "scale": [sx, sy, sz],
        }
    )
    matrix = axis_angle_matrix(axis, aa[3]) @ np.diag([sx, sy, sz])
    row = np.hstack([matrix, np.array(translation)[:, None]])
    parts.setdefault(part_key(part), []).append(row)
    return row


def part_key(part):
    return (part["mesh_url"], part["tex"], part.get("normal", ""), part.get("roughness", ""))


def instanced_tree_shapes(parts, out, far):
    """One instanced Shape per tree part, drawn up to far (then impostors take over).
    The source draws trees at full detail up to its Lod1_distance (218-226 m)."""
    band = f"\n          visibilityRange 0 {far:.1f}" if far else ""
    nodes = []
    for i, ((mesh, tex, normal, roughness), rows) in enumerate(sorted(parts.items())):
        url = f"meshes/instances_tree_{i}.bin"
        np.asarray(rows, "<f4").tofile(out / url)
        nodes.append(
            f"""Shape {{
{shape_fields(mesh, tex, normal, roughness)}
          instancesUrl [ "{url}" ]{band}
        }}"""
        )
    return nodes


# Trees beyond this distance are drawn as impostors (tools/bake_impostors.py). A view
# covers the capture sphere's diameter; at this distance on a 1080-line screen with the
# viewer's 1 rad field of view, a metre spans about 12 pixels.
IMPOSTOR_DISTANCE = 150.0
IMPOSTOR_PIXELS_PER_METRE = 12.0
IMPOSTOR_FRAMES = 8
# Coverage an impostor texel needs to be drawn. Full trees keep a needle texel whose mipmapped
# alpha, scaled by 1 + mip / 4 (Webots patch 0004), reaches 0.5: past 150 m (mip 6 and up)
# about 0.2 of it covered.
IMPOSTOR_ALPHA_CUTOFF = 0.2
IMPOSTOR_QUAD = """# Impostor quad (Webots Shape.impostor): corners (+-1, +-1, 0).
v -1 -1 0
v 1 -1 0
v 1 1 0
v -1 1 0
vt 0 0
vt 1 0
vt 1 1
vt 0 1
vn 0 0 1
f 1/1/1 2/2/1 3/3/1
f 1/1/1 3/3/1 4/4/1
"""


def dilate(color, alpha, steps=16):
    """Spread colours into empty texels so filtering never pulls in black."""
    valid = (alpha > 1e-3).astype(np.float32)
    color = color * valid[..., None]
    for _ in range(steps):
        pad_c = np.pad(color, ((1, 1), (1, 1), (0, 0)), mode="edge")
        pad_v = np.pad(valid, 1, mode="edge")
        acc = sum(pad_c[1 + dy:pad_c.shape[0] - 1 + dy, 1 + dx:pad_c.shape[1] - 1 + dx]
                  for dy in (-1, 0, 1) for dx in (-1, 0, 1))
        weight = sum(pad_v[1 + dy:pad_v.shape[0] - 1 + dy, 1 + dx:pad_v.shape[1] - 1 + dx]
                     for dy in (-1, 0, 1) for dx in (-1, 0, 1))
        grow = (valid == 0) & (weight > 0)
        color[grow] = acc[grow] / weight[grow][:, None]
        valid = np.maximum(valid, grow.astype(np.float32))
    fill = color[valid > 0].mean(0) if valid.any() else np.zeros(color.shape[-1])
    color[valid == 0] = fill
    return color


def impostor_atlases(build, out, variant, radius):
    """Albedo+alpha and normal atlases, sized so a view has about the screen's pixels
    at the impostor distance."""
    data = np.load(build / f"impostor_{variant}.npz")
    alpha = data["alpha"]
    safe = np.maximum(alpha, 1e-6)[..., None]
    albedo = np.clip(data["albedo"] / safe, 0, 1)
    albedo = np.where(albedo <= 0.0031308, 12.92 * albedo, 1.055 * albedo ** (1 / 2.4) - 0.055)
    # The mean normal over each texel's needles, kept unnormalized: its length says how much
    # they agree, which the impostor shader's foliage lighting uses.
    normal = np.clip(data["normal"] / safe * 2 - 1, -1, 1)
    depth = np.clip(data["depth"] / safe[..., 0], 0, 1)
    # Power-of-two views: Webots would rescale any other atlas size.
    view = int(np.clip(2 ** np.ceil(np.log2(2 * radius * IMPOSTOR_PIXELS_PER_METRE)), 32, 256))
    size = (IMPOSTOR_FRAMES * view,) * 2
    color = Image.fromarray(np.round(np.dstack([dilate(albedo, alpha), alpha]) * 255).astype(np.uint8), "RGBA")
    color.resize(size, Image.Resampling.LANCZOS).save(out / f"meshes/impostor_{variant}.png")
    # Normals (RGB) and depth (A) shade the crown softly: half the views' resolution is enough.
    filled = dilate(np.dstack([normal * 0.5 + 0.5, depth]), alpha)
    Image.fromarray(np.round(filled * 255).astype(np.uint8), "RGBA").resize(
        (size[0] // 2, size[1] // 2), Image.Resampling.LANCZOS).save(out / f"meshes/impostor_{variant}_normal.png")


def impostor_shapes(build, out, visual_trees, groups):
    """Declare the variants for tools/bake_impostors.py; once baked, one instanced impostor Shape
    per variant and group. groups: (rows, variants, near, far, suffix), each drawn from near to far
    metres from the viewer (0: no end). Returns the Shapes (empty before the bake)."""
    declared = {v: [{"mesh": p["mesh_url"], "tex": p["tex"], "normal": p.get("normal", "")} for p in parts]
                for v, parts in visual_trees.items()}
    (build / "impostor_variants.json").write_text(json.dumps(declared, indent=1, sort_keys=True))
    baked_path = build / "impostors.json"
    baked = json.loads(baked_path.read_text()) if baked_path.exists() else {}
    if not declared.keys() <= baked.keys():
        return []
    for variant in declared:  # a bake from an older capture lacks passes: rebake first
        with np.load(build / f"impostor_{variant}.npz") as data:
            if not {"albedo", "normal", "depth", "alpha"} <= set(data.files):
                return []
    (out / "meshes/impostor_quad.obj").write_text(IMPOSTOR_QUAD)
    nodes = []
    for variant in sorted(declared):
        sphere = baked[variant]
        impostor_atlases(build, out, variant, sphere["radius"])
        for rows, variants, near, far, suffix in groups:
            # Instance space = capture space: the tree's frame, moved to the sphere's centre, scaled by its radius.
            placed = rows[np.array([v == variant for v in variants], bool)]
            if not len(placed):
                continue
            capture = np.hstack([np.eye(3) * sphere["radius"], np.array(sphere["center"])[:, None]])
            instances = np.einsum("nab,bc->nac", placed[:, :, :3], capture)
            instances[:, :, 3] += placed[:, :, 3]
            url = f"meshes/instances_impostor_{variant}{suffix}.bin"
            instances.astype("<f4").tofile(out / url)
            nodes.append(f"""Shape {{
          appearance PBRAppearance {{
            baseColorMap ImageTexture {{ url "meshes/impostor_{variant}.png" }}
            normalMap ImageTexture {{ url "meshes/impostor_{variant}_normal.png" }}
            roughness 0.9
            metalness 0
            alphaCutoff {IMPOSTOR_ALPHA_CUTOFF}
          }}
          geometry Mesh {{ url "meshes/impostor_quad.obj" }}
          instancesUrl [ "{url}" ]
          visibilityRange {near:.1f} {far:.1f}
          castShadows FALSE
          impostor TRUE
        }}""")
    return nodes


CLUTTER_COUNT = 2000
CLUTTER_HEIGHT = 0.25  # metres


def mesh_bounds(path, cache={}):
    if path not in cache:
        vertices = np.array([line.split()[1:4] for line in path.read_text().splitlines() if line.startswith("v ")], float)
        cache[path] = vertices.min(0), vertices.max(0)
    return cache[path]


def height(path, row):
    """Vertical extent of a mesh placed by a 3 x 4 transform."""
    low, high = mesh_bounds(path)
    corners = np.array([[x, y, z] for x in (low[0], high[0]) for y in (low[1], high[1]) for z in (low[2], high[2])])
    z = corners @ row[2, :3]
    return z.max() - z.min()


def instance_cover(source, build, out, cover_index):
    """Place every source cover instance with GPU instancing.

    Each asset becomes one transforms file and two instanced Shapes: lod0 up to
    the source's lod0_distance, lod1 up to its lod1_distance, nothing beyond,
    exactly as the source scatter does around its camera. Returns (nodes,
    lod0 triangles placed, mesh urls).
    """
    assets = json.loads((build / "cover_assets.json").read_text())
    records = json.loads((build / "cover.json").read_text())
    mesh_urls = {}
    for name, meta in assets.items():
        if name not in cover_index:
            continue
        mesh_urls[name] = "meshes/" + meta["file"]
        copy_mesh(build / meta["file"], out / mesh_urls[name])
    # The source's normal and roughness maps, at the albedo's size.
    normal_maps, roughness_maps = {}, {}
    for name in mesh_urls:
        tex = next(iter(assets[name].get("textures", {}).values()), {})
        for key, mode, maps in (("normal", "RGB", normal_maps), ("roughness", "L", roughness_maps)):
            src = find_texture(source, tex.get(key))
            if src is None:
                continue
            url = "meshes/material_" + re.sub(r"\W", "_", src.name) + ".png"
            if not (out / url).exists():
                Image.open(src).convert(mode).resize((1024, 1024), Image.Resampling.LANCZOS).save(out / url)
            maps[name] = url

    groups = {}
    for r in records:
        groups.setdefault(r["asset"], []).append(r)
    nodes, total = [], 0
    for asset, placements in sorted(groups.items()):
        first = placements[0]
        rows = []
        for r in placements:
            # The instance basis is the source's world matrix (the mesh keeps source axes).
            basis = np.array(r["mat"], dtype=np.float64).reshape(3, 3)
            origin = enu(r["pos"])
            rows.append(np.hstack([basis, np.array(origin)[:, None]]))
            s, (ax, ay, az, ang) = cover_placement(r["mat"])
            # The canopy bake shades the ground through every lod0 placement.
            VISUAL_INSTANCES.append(
                {
                    "mesh": mesh_urls[asset],
                    "texture": cover_index[asset],
                    "translation": list(origin),
                    "rotation": [*enu([ax, ay, az]), ang],
                    "scale": [s, s, s],
                }
            )
        url = "meshes/instances_%s.bin" % re.sub(r"\W", "_", asset)
        mesh_file = lambda name: out / mesh_urls[name]
        rows = np.asarray(rows).reshape(-1, 3, 4)
        edge, _ = forest_backdrop.copies(rows, far=first["lod1_distance"], seed=len(nodes))
        edge, _ = forest_edge.lift(edge)
        np.concatenate([rows, edge]).astype("<f4").tofile(out / url)
        total += assets[asset]["tris"] * len(placements)
        bands = [(asset, 0.0, first["lod0_distance"])]
        if first["lod1"] != asset:
            bands.append((first["lod1"], first["lod0_distance"], first["lod1_distance"]))
        else:
            bands = [(asset, 0.0, first["lod1_distance"])]
        # Dense small clutter (the river bed's pebbles: ~11 k per mesh, under 0.25 m tall) casts
        # no cascade shadow: its shadows are a few centimetres, and in the maps such a carpet
        # shades itself black (ROADMAP, open bug). Ambient occlusion still grounds it.
        low = np.percentile([height(mesh_file(asset), row) for row in rows[:: max(1, len(rows) // 200)]], 90)
        shadow = not (len(placements) > CLUTTER_COUNT and low < CLUTTER_HEIGHT)
        for name, near, far in bands:
            nodes.append(
                f"""Shape {{
{shape_fields(mesh_urls[name], cover_index[name], normal_maps.get(name, ""), roughness_maps.get(name, ""), shadow)}
          instancesUrl [ "{url}" ]
          visibilityRange {near:.3f} {far:.3f}
        }}"""
            )
    return nodes, total, set(mesh_urls.values())


def write_world(out, solids, colliders, pad_y, manifest, terrain_shapes, edge_shapes, fog, light_occlusion=""):
    tree_solids = list(solids)
    tree_solids.extend(colliders)
    view_pos = "4 -5 2.6"
    view_ori = " ".join(str(v) for v in look_at([4, -5, 2.6], [0, 0, 0.8]))
    sky_fields = "\n".join(
        f'{face}Url [ "meshes/sky_{face}.hdr" ]\n{face}IrradianceUrl [ "meshes/sky_light_{face}.hdr" ]'
        for face in ("back", "bottom", "front", "left", "right", "top")
    )
    (out / "pine_forest.wbt").write_text(
        WORLD_TEMPLATE.format(
            tree_solids="\n".join(tree_solids),
            terrain_shapes=terrain_shapes,
            edge_shapes=edge_shapes,
            sky_fields=sky_fields,
            light_occlusion=light_occlusion,
            fog=fog,
            bounds_min=f"{REGION[0] - ORIGIN[0] + VIEW_MARGIN:.1f} {REGION[2] - ORIGIN[1] + VIEW_MARGIN:.1f} -50",
            bounds_max=f"{REGION[1] - ORIGIN[0] - VIEW_MARGIN:.1f} {REGION[3] - ORIGIN[1] - VIEW_MARGIN:.1f} {VIEW_CEILING}",
            pad_y=pad_y,
            drone_y=pad_y + 0.11,
            view_ori=view_ori,
            view_pos=view_pos,
        )
    )
    (out / ".pine_forest.wbproj").write_text(
        "Webots Project File version R2025a\n"
        "userInteractions: selectionDisabled::3dContextMenuDisabled::"
        "objectMoveDisabled::forceAndTorqueDisabled\n"
        # The drone's camera and LiDAR images stay off the view (they stream to ROS 2 instead).
        "renderingDevicePerspectives: Ironlark:camera;0;1;0;0\n"
        "renderingDevicePerspectives: Ironlark:lidar;0;1;0;0\n"
    )
    (out / "build_manifest.json").write_text(json.dumps(manifest, indent=1))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--build", required=True)
    parser.add_argument("--source", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    build = Path(args.build)
    source = Path(args.source)
    out = Path(args.out)
    (out / "meshes").mkdir(parents=True, exist_ok=True)
    manifest = json.loads((build / "manifest.json").read_text())

    # -- textures --
    print("textures", flush=True)
    visual_trees = prepare_visual_trees(source, build, out)
    import sky_faces

    for path in build.glob("sky_*.hdr"):
        if path.name.startswith("sky_light_"):  # the lighting sky, as the source's
            shutil.copyfile(path, out / "meshes" / path.name)
        else:  # the sky cameras see (sky_faces.CAMERA_SKY)
            sky_faces.write_hdr(out / "meshes" / path.name, sky_faces.read_hdr(path) * sky_faces.CAMERA_SKY)

    from forest_terrain import inner_rect

    forest_backdrop.BOUNDS = inner_rect(build)
    print("mirrored about", [round(b, 3) for b in forest_backdrop.BOUNDS], flush=True)

    # -- tree instances as Transforms --
    print("instances", flush=True)
    authored = json.loads((build / "authored_trees.json").read_text())
    properties = json.loads((build / "tree_properties.json").read_text())
    trees = []
    home = np.array([*manifest["home_blender"], 0])
    for record in authored:
        matrix = np.array(record["matrix"])
        props = properties[record["variant"]]
        # Exported mesh vertices have their minimum Z subtracted. Put that
        # offset back through the complete source instance transform.
        trees.append(
            {
                "variant": record["variant"],
                **tree_placement(matrix, props["base_z"], home),
            }
        )
    home_z = manifest["home_ground_z"]
    solids = []
    tree_parts = {}
    colliders = []
    tri_total = 0
    tree_rows = []
    for i, t in enumerate(trees):
        variant = t["variant"]
        pos = t["pos"]
        sx, sy, sz = t["scale"]
        ax, ay, az, angle = t["aa"]
        for part in visual_trees[variant]:
            row = place_tree_part(tree_parts, part, pos, (ax, ay, az, angle), (sx, sy, sz))
            tri_total += part["tris"]
        tree_rows.append(row)
        dist = math.hypot(pos[0], pos[2])
        if dist < COLLIDER_RADIUS:
            crown_info = properties[variant]
            center = np.array(enu(pos)) + t["matrix"][:3, :3] @ [
                0,
                0,
                crown_info["crown_base"] / 2,
            ]
            colliders.append(
                COLLIDER.format(
                    x=center[0],
                    y=center[2],
                    z=center[1],
                    rotation=" ".join(str(v) for v in (*enu(t["aa"][:3]), angle)),
                    h=crown_info["crown_base"] * sy,
                    r=max(0.05, crown_info["trunk_r"] * max(abs(sx), abs(sz))),
                    i=len(colliders),
                )
            )
    # The trees past the edges: each tree copied whole, so its parts turn together, and moved
    # onto the falling ground: on the near band, full trees for copies that can come within their
    # distance and impostors past it; further down the hillside, impostors (forest_valley).
    tree_rows = np.array(tree_rows)
    tree_variants = [t["variant"] for t in trees]
    copies, copied = forest_backdrop.copies(tree_rows, rings=2)
    edge, kept = forest_edge.lift(copies)
    hill, on_hill = forest_valley.hillside(copies, build)
    sources = copied[kept]
    near = forest_backdrop.fence_distance(edge[:, :, 3]) < IMPOSTOR_DISTANCE
    for row, original in zip(edge[near], sources[near]):
        for part in visual_trees[tree_variants[original]]:
            tree_parts[part_key(part)].append(row)
    impostors = impostor_shapes(build, out, visual_trees, [
        (np.concatenate([tree_rows, edge, hill]),
         tree_variants + [tree_variants[s] for s in sources] + [tree_variants[s] for s in copied[on_hill]],
         IMPOSTOR_DISTANCE - 1, 0.0, "")])
    solids.extend(instanced_tree_shapes(tree_parts, out, IMPOSTOR_DISTANCE if impostors else None))
    solids.extend(impostors)
    print(
        "trees", len(trees), "tris", tri_total, "colliders", len(colliders), flush=True
    )

    # -- ground cover instances --
    cover_index = build_cover_textures(source, build, out)
    cover_nodes, cover_tris, cover_meshes = instance_cover(source, build, out, cover_index)
    solids.extend(cover_nodes)
    tri_total += cover_tris
    print("cover tris", cover_tris, flush=True)

    copy_mesh(build / "terrain.obj", out / "meshes/terrain.obj")
    copy_mesh(build / "river.obj", out / "meshes/river.obj")

    # -- minimap scene --
    heights_grid = json.loads((build / "heights.json").read_text())
    scene = {
        "coordinate_system": "ENU",
        "bounds": [
            heights_grid["x"][0],
            -heights_grid["z"][1],
            heights_grid["x"][1],
            -heights_grid["z"][0],
        ],
        "trees": [{"position": [t["pos"][0], -t["pos"][2]]} for t in trees],
        # Export rows run max-z first; the minimap draws row 0 at min-z.
        "terrain": {"heights": heights_grid["grid"]},
        "cameras": CAMERAS,
        "home": [0, 0],
        "pad_top": home_z + 0.04,
    }
    (out / "scene.json").write_text(json.dumps(scene))

    manifest.pop("budgets", None)
    manifest.pop("seconds", None)
    manifest.update(
        {
            "stage": "authored forest geometry and baked materials",
            "build": "build_forest_world.py",
            "coordinate_system": "ENU",
            "foliage": "orthographic bakes of source twigs in source Geometry Nodes branch layout",
            "trees": len(trees),
            "tree_tris": tri_total - cover_tris,
            "cover_tris": cover_tris,
            "colliders": len(colliders),
            "collision_policy": "terrain mesh + trunk cylinders within %.0f m of home; "
            "distant trunks are visual-only until navigation lands" % COLLIDER_RADIUS,
        }
    )
    from forest_fog import fog_node
    from forest_terrain import build_terrain_tiles

    manifest["light_signature"] = light_signature(build, out)
    # Its mirrored-tile shapes are no longer drawn: the edge's own ground replaces them.
    terrain_shapes, _ = build_terrain_tiles(build, out, forest_backdrop.BOUNDS)
    edge_shapes = forest_edge.ground_shapes(out) + forest_valley.shapes(build, out)
    fog = fog_node(build, out, manifest["home_blender"])
    from forest_fog import light_occlusion_fields

    light_occlusion = light_occlusion_fields(build, out, manifest["home_blender"], forest_backdrop.BOUNDS)
    from forest_terrain import terrain_detail_fields

    light_occlusion += terrain_detail_fields(build, out, manifest["home_blender"], source, light_occlusion)
    write_world(out, solids, colliders, home_z + 0.02, manifest, terrain_shapes, "\n    ".join(edge_shapes), fog,
                light_occlusion)
    two_sided_materials(out)
    (out / "visual_instances.json").write_text(
        json.dumps(VISUAL_INSTANCES, separators=(",", ":"))
    )
    # This directory contains generated resources only. Remove replaced assets
    # after the new world has been written so rejected prototypes cannot linger.
    referenced = set(
        re.findall(r'"(meshes/[^"\n]+)"', (out / "pine_forest.wbt").read_text())
    )
    for path in (out / "meshes").iterdir():
        if path.is_file() and "meshes/" + path.name not in referenced:
            path.unlink()
    limit_textures(out / "meshes")
    bleed_alpha(out / "meshes")
    bleed_normals(out)
    compress_textures(build, out)
    print("wrote", out / "pine_forest.wbt", flush=True)


# HD textures, matching Poly Haven's official 1K downsamples of the same originals.
TEXTURE_LIMIT = 1024


def limit_textures(folder):
    """Downsample textures above the limit. Terrain tiles span 60 m each and are
    rebuilt separately from the source's tiling ground materials; impostor atlases
    hold 64 views, each sized to the screen at the impostor distance; the light occlusion
    layers stack five 0.2 m maps."""
    for path in folder.glob("*.png"):
        if path.name.startswith(("terrain_", "impostor_", "light_occlusion")):
            continue
        with Image.open(path) as image:
            if max(image.size) <= TEXTURE_LIMIT:
                continue
            image.load()
        image.thumbnail((TEXTURE_LIMIT, TEXTURE_LIMIT), Image.Resampling.LANCZOS)
        image.save(path)


def two_sided_materials(out):
    """Alpha masks only where a texture has transparency: Webots draws masked materials from
    both sides (patch 0017), as Blender does, and opaque ones culled. Meshes drawn only
    two-sided lose the back copy of each double-faced card, which that already shows."""
    path = out / "pine_forest.wbt"
    world = path.read_text()
    opaque = {}

    def transparent(url):
        if url not in opaque:
            with Image.open(out / url) as image:
                opaque[url] = "A" not in image.getbands() or image.getchannel("A").getextrema()[0] >= 250
        return not opaque[url]

    users = {}
    def material(match):
        block = match.group(0)
        texture = re.search(r'baseColorMap ImageTexture \{ url "([^"]+)"', block)
        mesh = re.search(r'geometry Mesh \{ url "([^"]+)"', block)
        if texture and "alphaCutoff" in block and not transparent(texture[1]):
            block = re.sub(r"\n\s*alphaCutoff [\d.]+", "", block)
        if mesh:
            users.setdefault(mesh[1], []).append("alphaCutoff" in block)
        return block

    world = re.sub(r"Shape \{.*?geometry Mesh \{ url \"[^\"]+\" \}", material, world, flags=re.S)
    path.write_text(world)
    dropped = 0
    for mesh, masked in users.items():
        if all(masked) and "impostor_" not in mesh:
            dropped += drop_back_copies(out / mesh)
    print("two-sided: dropped", dropped, "back copies", flush=True)


def drop_back_copies(path):
    """Remove the second of each pair of faces with the same corners and texture
    coordinates (a card and its reversed copy)."""
    lines = path.read_text().splitlines(keepends=True)
    positions = [l.split()[1:4] for l in lines if l.startswith("v ")]
    uvs = [l.split()[1:3] for l in lines if l.startswith("vt ")]
    seen, kept, dropped = set(), [], 0
    for line in lines:
        if line.startswith("f "):
            corners = []
            for vertex in line.split()[1:]:
                index = vertex.split("/")
                uv = tuple(uvs[int(index[1]) - 1]) if len(index) > 1 and index[1] else ()
                corners.append((tuple(positions[int(index[0]) - 1]), uv))
            key = frozenset(corners)
            if len(key) == len(corners) and key in seen:
                dropped += 1
                continue
            seen.add(key)
        kept.append(line)
    if dropped:
        path.write_text("".join(kept))
    return dropped


def write_bc7_dds(image, path):
    """DDS (DX10 header, BC7) with a box-filtered mip chain, as Webots would generate."""
    import struct

    import etcpak

    rgba = image.convert("RGBA")
    alpha = rgba.getchannel("A").getextrema()[0] < 250
    levels, level = [], rgba
    while True:
        w, h = level.size
        block = level if w % 4 == 0 and h % 4 == 0 else level.resize((max(4, w), max(4, h)), Image.Resampling.BOX)
        levels.append(etcpak.compress_bc7(np.ascontiguousarray(np.asarray(block)).tobytes(), *block.size))
        if w == 1 and h == 1:
            break
        level = level.resize((max(1, w // 2), max(1, h // 2)), Image.Resampling.BOX)
    width, height = rgba.size
    header = struct.pack("<4s7I44x", b"DDS ", 124, 0x1 | 0x2 | 0x4 | 0x1000 | 0x20000 | 0x80000, height, width,
                         len(levels[0]), 0, len(levels))
    header += struct.pack("<2I4s5I", 32, 0x4 | (0x1 if alpha else 0), b"DX10", 0, 0, 0, 0, 0)
    header += struct.pack("<5I", 0x1000 | 0x400000 | 0x8, 0, 0, 0, 0)
    header += struct.pack("<5I", 98, 3, 0, 1, 0)  # BC7_UNORM, 2D texture, one of it
    path.write_bytes(header + b"".join(levels))


# BC7 is visually lossless on these textures (41-47 dB) but not on the terrain's fine
# noise (22-32 dB with this encoder): the terrain stays uncompressed.
def compress_textures(build, out):
    """Webots patch 0024 loads BC7 DDS: a quarter of the RGBA8 memory, no CPU copy kept.
    Each power-of-two PNG the world uses becomes a DDS beside it (the PNG stays for the
    Blender tools), cached by content in the build folder."""
    path = out / "pine_forest.wbt"
    world = path.read_text()
    cache = build / "bc7"
    cache.mkdir(exist_ok=True)
    saved = 0
    for url in sorted(set(re.findall(r'url "(meshes/[^"]+\.png)"', world))):
        if Path(url).name.startswith("terrain_"):
            continue
        source = out / url
        with Image.open(source) as image:
            w, h = image.size
            if w & (w - 1) or h & (h - 1) or min(w, h) < 64:
                continue
            digest = hashlib.sha256(source.read_bytes()).hexdigest()[:24]
            cached = cache / f"{digest}.dds"
            if not cached.exists():
                write_bc7_dds(image, cached)
        dds = source.with_suffix(".dds")
        shutil.copyfile(cached, dds)
        world = world.replace(f'url "{url}"', f'url "{url[:-4]}.dds"')
        saved += w * h * 4 * 4 // 3 - dds.stat().st_size
    path.write_text(world)
    print("compressed textures: saves", saved // 2**20, "MB of graphics memory", flush=True)


def bleed_alpha(folder):
    """Give masked-out texels their opaque neighbours' colours. Mipmaps average colour
    over the mask: with near-black texels there (78% of a twig atlas), distant foliage
    darkened to a fifth of its colour. Nothing visible changes at full resolution."""
    for path in folder.glob("*.png"):
        if path.name.startswith("impostor_"):
            continue  # dilated when built
        with Image.open(path) as image:
            if image.mode != "RGBA":
                continue
            rgba = np.asarray(image, np.float32) / 255
        alpha = rgba[..., 3]
        if (alpha > 0.5).all():
            continue
        # Dilate from texels that stay opaque at any cutoff, a few texels at a time, then fill
        # the rest (which only deep mipmaps reach) with the mean opaque colour.
        color = dilate(rgba[..., :3], np.where(alpha > 0.5, alpha, 0), steps=8)
        keep = alpha[..., None] > 0.5
        rgba[..., :3] = np.where(keep, rgba[..., :3], color)
        Image.fromarray(np.round(rgba * 255).astype(np.uint8), "RGBA").save(path)


def bleed_normals(out):
    """Same for normal maps, under their base colour's mask: their mipmaps then average the
    needles' normals only, whose disagreement the renderer shades (Webots patch 0018)."""
    pairs = set(re.findall(r'baseColorMap ImageTexture \{ url "([^"]+)" \}\s*normalMap ImageTexture \{ url "([^"]+)" \}',
                           (out / "pine_forest.wbt").read_text()))
    for base, normal in sorted(pairs):
        if Path(normal).name.startswith("impostor_"):
            continue
        with Image.open(out / base) as image:
            if image.mode != "RGBA":
                continue
            alpha = image.getchannel("A")
        with Image.open(out / normal) as image:
            rgb = np.asarray(image.convert("RGB"), np.float32) / 255
        alpha = np.asarray(alpha.resize(rgb.shape[1::-1], Image.Resampling.BILINEAR), np.float32) / 255
        if (alpha > 0.5).all():
            continue
        keep = alpha[..., None] > 0.5
        rgb = np.where(keep, rgb, dilate(rgb, np.where(alpha > 0.5, alpha, 0), steps=8))
        Image.fromarray(np.round(rgb * 255).astype(np.uint8), "RGB").save(out / normal)


if __name__ == "__main__":
    main()
