"""Build the Loiter pine-forest Webots world from export_forest.py output.

Usage:
    python3 build_forest_world.py --build <forest-build> --source <textures>
        --out <worlds/pine_forest>

Converts the cache's Y-up mesh convention to the flight stack's ENU frame.
Keeps authored placements and source UVs, shares geometry and materials, and
writes the world, camera/map metadata and build manifest.

Deterministic: all randomness is seeded. Tree collision beyond the home
vicinity arrives with the navigation phase (no autonomy reads it yet).
"""

import argparse
import hashlib
import json
import math
import re
import shutil
import sys
from pathlib import Path

import numpy as np
from PIL import Image, ImageOps

sys.path.insert(
    0, str(Path(__file__).resolve().parents[1] / "controllers/flight_observer")
)
from minimap import look_at

COLLIDER_RADIUS = 25.0  # invisible trunk colliders within this range of home
# ---------------------------------------------------------------- obj helpers


def enu(v):
    """Legacy export cache (X,Y-up,Z) -> flight/world ENU, a proper rotation."""
    return (v[0], -v[2], v[1])


def copy_mesh(src, dst):
    with open(src) as fi, open(dst, "w") as fo:
        for line in fi:
            if line.startswith(("v ", "vn ")):
                kind, *v = line.split()
                fo.write(kind + " %.6f %.6f %.6f\n" % enu(list(map(float, v[:3]))))
            else:
                fo.write(line)


# Blender->Webots frame change as a rotation matrix (and its transpose).
C_FWD = np.array([[1, 0, 0], [0, 0, 1], [0, -1, 0]], dtype=np.float64)


def mat_to_axis_angle(m):
    """Rotation matrix -> Webots (x, y, z, angle). Re-orthogonalized."""
    u, _, vt = np.linalg.svd(np.array(m, dtype=np.float64).reshape(3, 3))
    r = u @ vt
    if np.linalg.det(r) < 0:
        u[:, -1] = -u[:, -1]
        r = u @ vt
    trace = (np.trace(r) - 1.0) / 2.0
    angle = math.acos(max(-1.0, min(1.0, trace)))
    if angle < 1e-9:
        return (0.0, 1.0, 0.0, 0.0)
    if angle > math.pi - 1e-6:
        # 180 deg: axis from the largest diagonal (sign from off-diagonals).
        k = int(np.argmax(np.diag(r)))
        axis = [r[k, 0], r[k, 1], r[k, 2]]
        axis[k] += 1.0
        n = math.sqrt(sum(a * a for a in axis))
        axis = [a / n for a in axis]
        return (axis[0], axis[1], axis[2], math.pi)
    s = 2.0 * math.sin(angle)
    return (
        (r[2, 1] - r[1, 2]) / s,
        (r[0, 2] - r[2, 0]) / s,
        (r[1, 0] - r[0, 1]) / s,
        angle,
    )


def cover_placement(mat_blender):
    """Cover instance basis -> (uniform scale, axis-angle) in Webots frame."""
    w = C_FWD @ np.array(mat_blender, dtype=np.float64).reshape(3, 3) @ C_FWD.T
    s = float(np.linalg.norm(w, axis=0).mean())
    return s, mat_to_axis_angle(w / s)


def tree_placement(matrix, base_z, home):
    """Retain an authored instance transform after rebasing its mesh at Z=0."""
    matrix = np.asarray(matrix, dtype=np.float64)
    position = matrix[:3, 3] + matrix[:3, :3] @ [0, 0, base_z] - home
    scales = np.linalg.norm(matrix[:3, :3], axis=0)
    rotation = matrix[:3, :3] / scales
    if np.linalg.det(rotation) < 0:
        scales[0] *= -1
        rotation[:, 0] *= -1
    return {
        "pos": C_FWD @ position,
        "scale": scales[[0, 2, 1]],
        "aa": mat_to_axis_angle(C_FWD @ rotation @ C_FWD.T),
        "matrix": matrix,
    }


WORLD_TEMPLATE = """#VRML_SIM R2025a utf8
# Generated by tools/build_forest_world.py — do not edit.

EXTERNPROTO "../.cache/Webots_Python/protos/Iris.proto"

WorldInfo {{
  title "Loiter — pine forest"
  basicTimeStep 2
  FPS 30
  randomSeed 7
  coordinateSystem "ENU"
}}
DEF LOITER_VIEW Viewpoint {{
  orientation {view_ori}
  position {view_pos}
  follow "Loiter Iris"
  fieldOfView 1.0
  exposure 1.0
  ambientOcclusionRadius 2
}}
Background {{
  skyColor [ 0.70 0.76 0.79 ]
  {sky_fields}
  luminosity 1
}}
Fog {{
  color 0.64 0.66 0.62
  visibilityRange 190
  fogType "EXPONENTIAL"
}}
# Tree shadows on the ground are baked into the terrain (canopy light).
# Webots' real-time stencil shadows would only add rock and drone shadows,
# at about seven times the frame cost.
# The source's two suns: strength in W/m² as intensity, linear color in sRGB.
DirectionalLight {{
  direction 0.272788 -0.814025 -0.512786
  color 1 0.9276 0.7243
  intensity 5
  castShadows FALSE
}}
DirectionalLight {{
  direction -0.148121 -0.845642 -0.512786
  color 1 0.8651 0.6049
  intensity 1
  castShadows FALSE
}}
Solid {{
  translation 0 0 0
  children [
    {terrain_shapes}
  ]
  name "terrain"
  boundingObject Mesh {{ url "meshes/terrain.obj" }}
}}
Solid {{
  translation 0 0 0
  children [
    Shape {{
      appearance PBRAppearance {{
        baseColor 0.10 0.23 0.26
        roughness 0.15
        metalness 0
      }}
      geometry Mesh {{ url "meshes/river.obj" }}
    }}
  ]
  name "river"
}}
{tree_solids}
# A visible home pad. Its top is flush with the flattened ground disc.
Solid {{
  translation 0 0 {pad_y:.3f}
  children [
    Shape {{
      appearance PBRAppearance {{
        baseColor 0.9 0.65 0.15
        roughness 1
        metalness 0
      }}
      geometry Cylinder {{ height 0.04 radius 0.8 }}
    }}
  ]
  name "home pad"
}}
DEF LOITER_DRONE Iris {{
  translation 0 0 {drone_y:.3f}
  name "Loiter Iris"
  controller "flight_bridge"
}}
Robot {{
  children [
    Display {{
      width 320
      height 294
      name "world map"
    }}
  ]
  name "flight evaluator"
  supervisor TRUE
  controller "flight_observer"
}}
"""

SHARED_SHAPES = {}
VISUAL_INSTANCES = []
COPIED_RESOURCES = {}


def copy_resource(source, out, convert_mesh=False):
    """Byte-identical assets get one URL, including across tree variants."""
    with source.open("rb") as stream:
        key = (hashlib.file_digest(stream, "sha256").hexdigest(), convert_mesh)
    if key not in COPIED_RESOURCES:
        url = "meshes/" + source.name
        if convert_mesh:
            copy_mesh(source, out / url)
        else:
            shutil.copyfile(source, out / url)
        COPIED_RESOURCES[key] = url
    return COPIED_RESOURCES[key]


def light_signature(build, out):
    """Invalidate canopy lighting when its actual geometry or alpha changes."""
    digest = hashlib.sha256(json.dumps(VISUAL_INSTANCES, sort_keys=True).encode())
    urls = {record[key] for record in VISUAL_INSTANCES for key in ("mesh", "texture")}
    paths = [out / url for url in sorted(urls)]
    paths += [
        build / "terrain.obj",
        Path(__file__).with_name("bake_forest_light.py"),
        Path(__file__).with_name("forest_terrain.py"),
    ]
    for path in paths:
        with path.open("rb") as stream:
            digest.update(hashlib.file_digest(stream, "sha256").digest())
    return digest.hexdigest()


def instance_node(**kw):
    """Share complete visual resources; transforms alone vary per instance."""
    x, y, z = enu([kw["x"], kw["y"], kw["z"]])
    ax, ay, az = enu([kw["ax"], kw["ay"], kw["az"]])
    sx, sy, sz = kw["sx"], kw["sz"], kw["sy"]
    mesh, tex = kw["mesh"], kw["tex"]
    normal = kw.get("normal", "")
    roughness = kw.get("roughness", "")
    VISUAL_INSTANCES.append(
        {
            "mesh": mesh,
            "texture": tex,
            "translation": [x, y, z],
            "rotation": [ax, ay, az, kw["ang"]],
            "scale": [sx, sy, sz],
        }
    )
    shadow = kw.get("shadow", False)
    key = (mesh, tex, normal, roughness, shadow)
    tag = "VISUAL_" + str(len(SHARED_SHAPES))
    if key in SHARED_SHAPES:
        shape = "USE " + SHARED_SHAPES[key]
    else:
        SHARED_SHAPES[key] = tag
        # All 53 source materials are alpha-hashed: mask texels, never blend them.
        normal_field = f'normalMap ImageTexture {{ url "{normal}" }}' if normal else ""
        roughness_field = (
            f'roughnessMap ImageTexture {{ url "{roughness}" }}' if roughness else ""
        )
        shape = f'''DEF {tag} Shape {{
          appearance PBRAppearance {{
            baseColorMap ImageTexture {{ url "{tex}" }}
            {normal_field}
            {roughness_field}
            roughness 0.9
            metalness 0
            alphaCutoff 0.5
          }}
          geometry Mesh {{ url "{mesh}" }}
          castShadows {"TRUE" if shadow else "FALSE"}
        }}'''
    return f"""Transform {{
      translation {x:.4f} {y:.4f} {z:.4f}
      rotation {ax:.6f} {ay:.6f} {az:.6f} {kw["ang"]:.6f}
      scale {sx:.5f} {sy:.5f} {sz:.5f}
      children [ {shape} ]
    }}"""


COLLIDER = """Solid {{
  translation {x:.3f} {z:.3f} {y:.3f}
  rotation {rotation}
  children [
  ]
  boundingObject Cylinder {{
    height {h:.2f}
    radius {r:.2f}
  }}
  name "trunk collider {i}"
}}
"""


def find_texture(source, image_name):
    """Resolve a Blender image name to a source PNG path."""
    if not image_name:
        return None
    image_name = re.sub(r"(\.png|\.jpg)\.\d+$", r"\1", image_name)
    candidates = [source / (image_name + ".png"), source / image_name]
    for c in candidates:
        if c.is_file():
            return c
    matches = sorted(source.glob(image_name + ".*"))
    return matches[0] if matches else None


def build_cover_textures(source, build, out):
    """One photographic material per atlas, shared across all asset variants."""
    assets = json.loads((build / "cover_assets.json").read_text())
    index, prepared = {}, {}
    for name, meta in assets.items():
        textures = meta.get("textures") or {}
        first = next(iter(textures.values()), {})
        diff, alpha = first.get("diff"), first.get("alpha")
        src = find_texture(source, diff) if diff else None
        if src is None:
            raise RuntimeError(f"Missing cover albedo: {name}: {diff}")
        key = (diff, alpha, first.get("invert_alpha", False))
        if key not in prepared:
            safe = "material_" + re.sub(r"\W", "_", diff) + ".png"
            img = Image.open(src).convert("RGB")
            img = img.resize((1024, 1024), Image.Resampling.LANCZOS)
            asrc = find_texture(source, alpha) if alpha else None
            if asrc:
                a = (
                    Image.open(asrc)
                    .convert("L")
                    .resize(img.size, Image.Resampling.LANCZOS)
                )
                if first.get("invert_alpha"):
                    a = ImageOps.invert(a)
                img.putalpha(a)
            img.save(out / "meshes" / safe)
            prepared[key] = "meshes/" + safe
        index[name] = prepared[key]
    return index


def prepare_visual_trees(source, build, out):
    """Source-authored branches and twigs, baked before tree evaluation."""
    meta = json.loads((build / "visual_trees.json").read_text())
    material_images = json.loads((build / "material_images.json").read_text())
    atlas = json.loads((build / "twig_atlas.json").read_text())
    prepared = {}
    for species, cards in atlas.items():
        img = Image.new("RGBA", (2048, 2048))
        normals = Image.new("RGB", (2048, 2048), (128, 128, 255))
        for card in cards:
            cell = (
                Image.open(build / card["file"])
                .convert("RGBA")
                .resize((512, 512), Image.Resampling.LANCZOS)
            )
            # Alpha is kept at full precision. No hard threshold erases needles.
            img.paste(cell, ((card["cell"] % 4) * 512, (card["cell"] // 4) * 512))
            if "normal" in card:
                cell = (
                    Image.open(build / card["normal"])
                    .convert("RGB")
                    .resize((512, 512), Image.Resampling.LANCZOS)
                )
                normals.paste(
                    cell, ((card["cell"] % 4) * 512, (card["cell"] // 4) * 512)
                )
        img.save(out / f"meshes/twigs_{species}.png")
        normals.save(out / f"meshes/twigs_{species}_normal.png")
    for variant, parts in meta["variants"].items():
        baked_path = build / f"baked_{variant}.json"
        baked = json.loads(baked_path.read_text()) if baked_path.exists() else {}
        for part in parts:
            part["mesh_url"] = copy_resource(
                build / part["file"], out, convert_mesh=True
            )
            if part.get("atlas", part["foliage"]):
                species = part.get(
                    "atlas_name", "pine" if "pine" in part["material"] else "fir"
                )
                part["tex"] = f"meshes/twigs_{species}.png"
                part["normal"] = f"meshes/twigs_{species}_normal.png"
                continue
            if part["material"] in baked:
                for suffix, key in [
                    ("diff", "tex"),
                    ("normal", "normal"),
                    ("rough", "roughness"),
                ]:
                    name = baked[part["material"]][suffix]
                    part[key] = copy_resource(build / name, out)
                continue
            material = part["material"].split(".")[0]
            for suffix, key in [
                ("diff", "tex"),
                ("nor_gl", "normal"),
                ("rough", "roughness"),
            ]:
                images = material_images.get(part["material"], [])
                match = next(
                    (
                        n
                        for n in images
                        if {"tex": "diff", "normal": "nor_gl", "roughness": "rough"}[
                            key
                        ]
                        in n
                    ),
                    None,
                )
                src = (
                    find_texture(source, match)
                    if match
                    else source / f"{material}_{suffix}.png"
                )
                if src is None or not src.exists():
                    if key == "tex":
                        raise RuntimeError(f"Missing tree material {src}")
                    continue
                alpha = (
                    find_texture(source, part.get("textures", {}).get("alpha", ""))
                    if key == "tex" and part["foliage"]
                    else None
                )
                cache_key = (
                    src,
                    alpha,
                    part.get("textures", {}).get("invert_alpha", False),
                )
                if cache_key in prepared:
                    part[key] = prepared[cache_key]
                    continue
                name = f"material_{material}_{suffix}.png"
                img = (
                    Image.open(src)
                    .convert("RGB")
                    .resize((1024, 1024), Image.Resampling.LANCZOS)
                )
                if key == "tex" and part["foliage"]:
                    if alpha:
                        mask = (
                            Image.open(alpha)
                            .convert("L")
                            .resize(img.size, Image.Resampling.LANCZOS)
                        )
                        if part["textures"].get("invert_alpha"):
                            mask = ImageOps.invert(mask)
                        img.putalpha(mask)
                img.save(out / "meshes" / name)
                part[key] = "meshes/" + name
                prepared[cache_key] = part[key]
    return meta["variants"]


def instance_cover(build, out, cover_index):
    """Copy each cover asset mesh once; place instances as Transforms.

    Returns (nodes, placed_tris, mesh_urls). Webots loads each unique
    mesh once no matter how many Transforms reference it.
    """
    assets = json.loads((build / "cover_assets.json").read_text())
    records = json.loads((build / "cover.json").read_text())
    mesh_urls = {}
    for name, meta in assets.items():
        if name not in cover_index:
            continue
        mesh_urls[name] = "meshes/" + meta["file"]
        copy_mesh(build / meta["file"], out / mesh_urls[name])
    normal_maps = {}
    for name in mesh_urls:
        tex = next(iter(assets[name].get("textures", {}).values()), {})
        normal_src = (
            Path(out).resolve().parents[2]
            / ".cache/pine-forest/source/textures"
            / tex.get("normal", "missing")
        )
        if normal_src.exists():
            url = "meshes/material_" + normal_src.name
            if not (out / url).exists():
                img = Image.open(normal_src).convert("RGB")
                img.thumbnail((1024, 1024), Image.Resampling.LANCZOS)
                img.save(out / url)
            normal_maps[name] = url
    nodes, total = [], 0
    for i, r in enumerate(records):
        if r["asset"] not in mesh_urls:
            continue
        s, (ax, ay, az, ang) = cover_placement(r["mat"])
        x, y, z = r["pos"]
        nodes.append(
            instance_node(
                x=x,
                y=y,
                z=z,
                ax=ax,
                ay=ay,
                az=az,
                ang=ang,
                sx=s,
                sy=s,
                sz=s,
                tex=cover_index[r["asset"]],
                mesh=mesh_urls[r["asset"]],
                normal=normal_maps.get(r["asset"], ""),
                shadow=(
                    assets[r["asset"]]["tris"] <= 21845
                    and (
                        "rock" in r["asset"]
                        or "dead_tree" in r["asset"]
                        or "tree_trunk" in r["asset"]
                    )
                ),
                tag="C_%s_%d" % (re.sub(r"\W", "_", r["asset"]), i),
            )
        )
        total += assets[r["asset"]]["tris"]
    print("cover instances", len(records), flush=True)
    return nodes, total, set(mesh_urls.values())


def write_world(out, solids, colliders, pad_y, manifest, terrain_shapes):
    tree_solids = list(solids)
    tree_solids.extend(colliders)
    view_pos = "4 -5 2.6"
    view_ori = " ".join(str(v) for v in look_at([4, -5, 2.6], [0, 0, 0.8]))
    sky_fields = "\n".join(
        f'{face}Url [ "meshes/sky_{face}.hdr" ]\n{face}IrradianceUrl [ "meshes/sky_light_{face}.hdr" ]'
        for face in ("back", "bottom", "front", "left", "right", "top")
    )
    (out / "pine_forest.wbt").write_text(
        WORLD_TEMPLATE.format(
            tree_solids="\n".join(tree_solids),
            terrain_shapes=terrain_shapes,
            sky_fields=sky_fields,
            pad_y=pad_y,
            drone_y=pad_y + 0.11,
            view_ori=view_ori,
            view_pos=view_pos,
        )
    )
    (out / ".pine_forest.wbproj").write_text(
        "Webots Project File version R2025a\n"
        "userInteractions: selectionDisabled::3dContextMenuDisabled::"
        "objectMoveDisabled::forceAndTorqueDisabled\n"
    )
    (out / "build_manifest.json").write_text(json.dumps(manifest, indent=1))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--build", required=True)
    parser.add_argument("--source", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    build = Path(args.build)
    source = Path(args.source)
    out = Path(args.out)
    (out / "meshes").mkdir(parents=True, exist_ok=True)
    manifest = json.loads((build / "manifest.json").read_text())

    # -- textures --
    print("textures", flush=True)
    visual_trees = prepare_visual_trees(source, build, out)
    for path in build.glob("sky_*.hdr"):
        shutil.copyfile(path, out / "meshes" / path.name)

    # -- tree instances as Transforms --
    print("instances", flush=True)
    authored = json.loads((build / "authored_trees.json").read_text())
    properties = json.loads((build / "tree_properties.json").read_text())
    trees = []
    home = np.array([*manifest["home_blender"], 0])
    for record in authored:
        matrix = np.array(record["matrix"])
        props = properties[record["variant"]]
        # Exported mesh vertices have their minimum Z subtracted. Put that
        # offset back through the complete source instance transform.
        trees.append(
            {
                "variant": record["variant"],
                **tree_placement(matrix, props["base_z"], home),
            }
        )
    home_z = manifest["home_ground_z"]
    solids = []
    colliders = []
    tri_total = 0
    for i, t in enumerate(trees):
        variant = t["variant"]
        pos = t["pos"]
        sx, sy, sz = t["scale"]
        ax, ay, az, angle = t["aa"]
        for part in visual_trees[variant]:
            solids.append(
                instance_node(
                    x=pos[0],
                    y=pos[1],
                    z=pos[2],
                    ax=ax,
                    ay=ay,
                    az=az,
                    ang=angle,
                    sx=sx,
                    sy=sy,
                    sz=sz,
                    tex=part["tex"],
                    normal=part.get("normal", ""),
                    roughness=part.get("roughness", ""),
                    mesh=part["mesh_url"],
                    # Canopy light is ray-traced through the actual alpha masks.
                    shadow=False,
                )
            )
            tri_total += part["tris"]
        dist = math.hypot(pos[0], pos[2])
        if dist < COLLIDER_RADIUS:
            crown_info = properties[variant]
            center = np.array(enu(pos)) + t["matrix"][:3, :3] @ [
                0,
                0,
                crown_info["crown_base"] / 2,
            ]
            colliders.append(
                COLLIDER.format(
                    x=center[0],
                    y=center[2],
                    z=center[1],
                    rotation=" ".join(str(v) for v in (*enu(t["aa"][:3]), angle)),
                    h=crown_info["crown_base"] * sy,
                    r=max(0.05, crown_info["trunk_r"] * max(abs(sx), abs(sz))),
                    i=len(colliders),
                )
            )
    print(
        "trees", len(trees), "tris", tri_total, "colliders", len(colliders), flush=True
    )

    # -- ground cover instances --
    cover_index = build_cover_textures(source, build, out)
    cover_nodes, cover_tris, cover_meshes = instance_cover(build, out, cover_index)
    solids.extend(cover_nodes)
    tri_total += cover_tris
    print("cover tris", cover_tris, flush=True)

    copy_mesh(build / "terrain.obj", out / "meshes/terrain.obj")
    copy_mesh(build / "river.obj", out / "meshes/river.obj")

    # -- minimap scene --
    heights_grid = json.loads((build / "heights.json").read_text())
    scene = {
        "coordinate_system": "ENU",
        "bounds": [
            heights_grid["x"][0],
            -heights_grid["z"][1],
            heights_grid["x"][1],
            -heights_grid["z"][0],
        ],
        "trees": [{"position": [t["pos"][0], -t["pos"][2]]} for t in trees],
        # Export rows run max-z first; the minimap draws row 0 at min-z.
        "terrain": {"heights": heights_grid["grid"]},
        "cameras": {
            "drone": {"eye": [4, 2.6, 5], "target": [0, 0.8, 0]},
            "overview": {"eye": [-45, 55, -100], "target": [-45, 0, -40]},
            "forest": {
                "eye": [-13.944526, 0.922303, -32.4402],
                "target": [-23.765966, 2.18279, -33.83680],
            },
        },
        "home": [0, 0],
        "pad_top": home_z + 0.04,
    }
    for camera in scene["cameras"].values():
        camera["eye"] = enu(camera["eye"])
        camera["target"] = enu(camera["target"])
    (out / "scene.json").write_text(json.dumps(scene))

    manifest.pop("budgets", None)
    manifest.pop("seconds", None)
    manifest.update(
        {
            "stage": "authored forest geometry and baked materials",
            "build": "build_forest_world.py",
            "coordinate_system": "ENU",
            "foliage": "orthographic bakes of source twigs in source Geometry Nodes branch layout",
            "trees": len(trees),
            "tree_tris": tri_total - cover_tris,
            "cover_tris": cover_tris,
            "colliders": len(colliders),
            "collision_policy": "terrain mesh + trunk cylinders within %.0f m of home; "
            "distant trunks are visual-only until navigation lands" % COLLIDER_RADIUS,
        }
    )
    from forest_terrain import build_terrain_tiles

    manifest["light_signature"] = light_signature(build, out)
    terrain_shapes = build_terrain_tiles(build, out, manifest["light_signature"])
    write_world(out, solids, colliders, home_z + 0.02, manifest, terrain_shapes)
    (out / "visual_instances.json").write_text(
        json.dumps(VISUAL_INSTANCES, separators=(",", ":"))
    )
    # This directory contains generated resources only. Remove replaced assets
    # after the new world has been written so rejected prototypes cannot linger.
    referenced = set(
        re.findall(r'"(meshes/[^"\n]+)"', (out / "pine_forest.wbt").read_text())
    )
    for path in (out / "meshes").iterdir():
        if path.is_file() and "meshes/" + path.name not in referenced:
            path.unlink()
    limit_textures(out / "meshes")
    print("wrote", out / "pine_forest.wbt", flush=True)


# HD textures, matching Poly Haven's official 1K downsamples of the same originals.
TEXTURE_LIMIT = 1024


def limit_textures(folder):
    """Downsample textures above the limit. Terrain tiles span 60 m each and are
    rebuilt separately from the source's tiling ground materials."""
    for path in folder.glob("*.png"):
        if path.name.startswith("terrain_"):
            continue
        with Image.open(path) as image:
            if max(image.size) <= TEXTURE_LIMIT:
                continue
            image.load()
        image.thumbnail((TEXTURE_LIMIT, TEXTURE_LIMIT), Image.Resampling.LANCZOS)
        image.save(path)


if __name__ == "__main__":
    main()
